### ISSUE TITLE
Cleaning Data & Automating Tasks -- Session 1

### ISSUE THREAD

**Issue by nick-ulle** [ucdavisdatalab/workshop_intermediate_r#3]
[Topic schedule](https://docs.google.com/spreadsheets/d/1cldCE7Pmx6PxzwQnvZlztJWG1YP1i5O03uzY61v7i5I/edit#gid=0)

This session is tentatively titled "Date & String Processing".

TODO:
* [x] Add learning goals
* [x] Write an introduction
* [x] Import content from R Basics appendix ("Date Processing", "String Processing")
* [x] Import content from Adventures in Data Science ("String Processing")
* [x] Organize and edit imported content for flow
* [x] ~~Develop new content about [hms][] and [clock][]. Probably just an overview of R's numerous packages/classes for representing dates and times, but maybe more? Probably not enough time for a deep dive...~~
* [x] Write case study for date processing
    + Possibly about combining ocean temperature data from [NOAA NDBC][ndbc] and from [CALOOS][] (they use different date formats)
* [x] Write case study for string processing (possibly using part of the [spam emails data set][spam] to demonstrate extracting emails)
    + Or extracting phone numbers from [NHTSA Recall Data][recalls]
* [x] Prepare/post data sets for students

[ndbc]: https://www.ndbc.noaa.gov/
[CALOOS]: https://data.caloos.org/
[recalls]: https://www.nhtsa.gov/nhtsa-datasets-and-apis
[spam]: https://spamassassin.apache.org/old/publiccorpus/
[hms]: https://hms.tidyverse.org/index.html
[clock]: https://clock.r-lib.org/

**Comment by nick-ulle** [comment]
@t-shoemaker Drawing your attention in case you have any suggestions for interesting not-too-large text data sets to use for a case study in extracting something via regular expressions.

**Comment by wes-brooks** [comment]
Maddening: https://learn.microsoft.com/en-us/office/troubleshoot/excel/wrongly-assumes-1900-is-leap-year

**Comment by t-shoemaker** [comment]
> @t-shoemaker Drawing your attention in case you have any suggestions for interesting not-too-large text data sets to use for a case study in extracting something via regular expressions.

A few options:
+ Menus: http://curatingmenus.org/data_dictionary/
+ Enron emails: http://www.cs.cmu.edu/~enron/
+ NY State comptroller's business listings (would be great for column-wise data extraction exercises): https://ny.newnycontracts.com/FrontEnd/SearchCertifiedDirectory.asp
+ Blurb Genre Collection (in XML): https://www.inf.uni-hamburg.de/en/inst/ab/lt/resources/data/blurb-genre-collection.html

**Comment by nick-ulle** [comment]
Finished as of 0cdd9c026ab2ac3ecacac6ff01db67bd852919ef
